<%@ Page Language="VB" AutoEventWireup="false" CodeFile="ExportJsonData.aspx.vb" Inherits="GestionQuestionnaire_ExportJsonData" %>

<!DOCTYPE html>

<html>
<head runat="server">
    <title>Export JSON Data</title>
    <!-- For-Mobile-Apps-and-Meta-Tags -->
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <style type="text/css">
        .headline {
            text-shadow: 1px 3px 5px rgba(0, 0, 0, 0.5);
            font-weight: 300;
            -webkit-font-smoothing: antialiased !important;
            opacity: 0.8;
            margin: 10px 0 30px 0;
            font-size: 30px;
        }

        html, body {
            overflow-x: hidden !important;
            font-family: 'Source Sans Pro', sans-serif;
            -webkit-font-smoothing: antialiased;
            min-height: 100%;
            background: #FFF;
        }
    </style>
    
    <script type="text/javascript">
        function Open_Window(page, _width, _height) {
            var largeurEcran = (screen.width - _width) / 2;
            var hauteurEcran = (screen.height - _height) / 2;
            window.open(page, 'APIDashBord', ' width=' + _width + ', height=' + _height + ', top=' + hauteurEcran + ', left=' + largeurEcran + ', toolbar=0, location=0, directories=0, status=0, scrollbars=1, resizable=0, copyhistory=0, menuBar=0')
        }
        function OpenWindow(page) {
            window.open(page, '_self')
        }
        function OpenWindowBlank(page) {
            window.open(page, '_blank')
        }
    </script>
</head>
<body>
  
    <form id="form1" runat="server">
        <!-- Automatic element centering using js -->
        <div class="center" style="cursor:pointer;" onclick="OpenWindow('./Default.aspx')">
            <!-- /.headline -->
            <!-- User name -->
            <div class="lockscreen-name" id="time" style="text-align: center;color:#FFF;">
                <!-- Time auto generated by js -->
            </div>
            <!-- START LOCK SCREEN ITEM -->
            <div class="lockscreen-item">
                <!-- lockscreen image -->
                <div class="lockscreen-image" style="text-align: center; display: block;">
                    <asp:Image ID="imglogo_chant_chorale_et_groupe" runat="server" ImageUrl="~/images/logo_rgph.png" />
                    <div style="/* text-align: center; *//* display: block; *//* width: 100%; *//* position: absolute;*/ margin-top: -20px;">
                        <asp:Image ID="Image1" runat="server" Style="" ImageUrl="~/images/preloaders.gif" />
                    </div>
                </div>
            </div>
            <div class="headline text-center" style="text-align: center;">
               API : RGPH - Questionnaire
            </div> 
            <Msg:msgBox ID="Dialogue" runat="server" />
            <asp:Panel runat="server" ID="Panel_Msg" Visible="false">
                <div id="DIV_Msg" runat="server" class="alert alert-warning alert-dismissable">
                    <i id="Icon_Msg" runat="server" class="fa fa-warning"></i>
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <asp:Image ID="Image_Msg" runat="server" />
                    <asp:Label ID="Label_Msg" runat="server" Text=""></asp:Label>
                </div>
            </asp:Panel>
            <!-- /.lockscreen-item -->
        </div>
        <!-- /.center -->
        <!-- jQuery 2.0.2 -->
        <script src="../AdminLTE-master/ajax/libs/jquery/2.0.2/jquery.min.js"></script>
        <!-- Bootstrap -->
        <script src="../AdminLTE-master/js/bootstrap.min.js" type="text/javascript"></script>
    </form>
    <!-- page script -->
    <script type="text/javascript">
        $(function () {
            startTime();
            $(".center").center();
            $(window).resize(function () {
                $(".center").center();
            });
        });

        /*  */
        function startTime() {
            var today = new Date();
            var h = today.getHours();
            var m = today.getMinutes();
            var s = today.getSeconds();

            // add a zero in front of numbers<10
            m = checkTime(m);
            s = checkTime(s);

            //Check for PM and AM
            var day_or_night = (h > 11) ? "PM" : "AM";

            //Convert to 12 hours system
            if (h > 12)
                h -= 12;

            //Add time to the headline and update every 500 milliseconds
            $('#time').html(h + ":" + m + ":" + s + " " + day_or_night);
            setTimeout(function () {
                startTime()
            }, 500);
        }

        function checkTime(i) {
            if (i < 10) {
                i = "0" + i;
            }
            return i;
        }

        /* CENTER ELEMENTS IN THE SCREEN */
        jQuery.fn.center = function () {
            this.css("position", "absolute");
            this.css("top", Math.max(0, (($(window).height() - $(this).outerHeight()) / 2) +
                        $(window).scrollTop()) - 30 + "px");
            this.css("left", Math.max(0, (($(window).width() - $(this).outerWidth()) / 2) +
                        $(window).scrollLeft()) + "px");
            return this;
        }
    </script>
    <%--<form id="form1" runat="server">
        <div>

           
        </div>
    </form>--%>
</body>
</html>
